neoforgeVersion=26.3.0.43-beta
neoForge.parchment.minecraftVersion=1.21.9
neoForge.parchment.mappingsVersion=2025.10.05

# Mod Properties
mavenGroup=de.mari_023
modID=ae2wtlib
ae2wtlibCurrentMajor=26

ae2Version=26.3.1-alpha
curiosVersion=17.0.0-beta.2+26.3

reiVersion=26.1.819
architecturyVersion=20.0.10
jeiMinecraftVersion=26.3
jeiVersion=31.9.0.56
emiVersion=1.1.22
emiMinecraftVersion=1.21.1

runtimeItemlistMod=jei

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
# Temp fix for Spotless
# https://github.com/diffplug/spotless/issues/834
org.gradle.jvmargs= \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
