modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/Mari023/AE2WirelessTerminalLibrary/issues"
license = "MIT"

[[mods]]
modId = "ae2wtlib"
version = "${version}"
displayName = "AE2WTLib"
authors = "mari_023, Ridanisaurus"
description = '''
Adds Wireless versions of ae2 Terminals with infinite range capabilities.
'''
logoFile = "icon.png"

[[dependencies.ae2wtlib]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.ae2wtlib]]
modId = "minecraft"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.ae2wtlib]]
modId = "ae2"
mandatory = true
versionRange = "[${ae2_version},16.0.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ae2wtlib]]
modId = "cloth_config"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ae2wtlib]]
modId = "architectury"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ae2wtlib]]
modId = "curios"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"