modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Mari023/AE2WirelessTerminalLibrary/issues"
license = "MIT"

[[mods]]
modId = "ae2wtlib"
version = "${version}"
displayName = "AE2WTLib"
authors = "mari_023, Ridanisaurus"
description = '''
Adds Wireless versions of ae2 Terminals with infinite range capabilities.
'''
updateJSONURL = "https://api.modrinth.com/updates/applied-energistics-2-wireless-terminals/forge_updates.json?neoforge=only"
logoFile = "icon.png"

[[mixins]]
config="ae2wtlib.mixins.json"

[[dependencies.ae2wtlib]]
modId = "neoforge"
type="REQUIRED"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.ae2wtlib]]
modId = "minecraft"
type="REQUIRED"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.ae2wtlib]]
modId = "ae2"
type="REQUIRED"
versionRange = "[${ae2_version},19.0.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ae2wtlib]]
modId = "curios"
type="REQUIRED"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"