modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Mari023/AE2WirelessTerminalLibrary/issues"
license = "MIT"

[[mods]]
modId = "ae2wtlib_api"
version = "${version}"
displayName = "AE2WTLib API"
authors = "mari_023, Ridanisaurus"
description = '''
API for adding wireless terminals with easy integration with AE2wtlib.
'''
logoFile = "icon.png"
logoBlur=false

[[dependencies.ae2wtlib_api]]
modId = "neoforge"
type="REQUIRED"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.ae2wtlib_api]]
modId = "minecraft"
type="REQUIRED"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.ae2wtlib_api]]
modId = "ae2"
type="REQUIRED"
versionRange = "[${ae2_version},20.0.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ae2wtlib]]
modId = "ae2wtlib"
type="INCOMPATIBLE"
versionRange = "(,19.1.0-alpha)"
ordering = "NONE"
side = "BOTH"
reason = "breaking changes in the ae2wtlib api"