name: build neoforge
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: gradle assemble
        env:
          HASH: $(git rev-parse --short "$GITHUB_SHA")

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/**.jar

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true

      - name: format
        run: gradle spotlessCheck
